# CMake generated Testfile for 
# Source directory: /home/user/TapTools
# Build directory: /home/user/TapTools/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("source/projects/tap.adsr_tilde")
subdirs("source/projects/tap.autothru_tilde")
subdirs("source/projects/tap.biquadcalc")
subdirs("source/projects/tap.bits")
subdirs("source/projects/tap.buffer.peak_tilde")
subdirs("source/projects/tap.buffer.record_tilde")
subdirs("source/projects/tap.buffer.snap_tilde")
subdirs("source/projects/tap.change")
subdirs("source/projects/tap.comb_tilde")
subdirs("source/projects/tap.count_tilde")
subdirs("source/projects/tap.counter_tilde")
subdirs("source/projects/tap.crossfade_tilde")
subdirs("source/projects/tap.dcblock_tilde")
subdirs("source/projects/tap.elixir_tilde")
subdirs("source/projects/tap.fft.binmodulator_tilde")
subdirs("source/projects/tap.fft.list_tilde")
subdirs("source/projects/tap.fft.normalize_tilde")
subdirs("source/projects/tap.fourpole_tilde")
subdirs("source/projects/tap.gang")
subdirs("source/projects/tap.inquisitor")
subdirs("source/projects/tap.limi_tilde")
subdirs("source/projects/tap.list.index")
subdirs("source/projects/tap.multitap_tilde")
subdirs("source/projects/tap.noise_tilde")
subdirs("source/projects/tap.pan_tilde")
subdirs("source/projects/tap.prime")
subdirs("source/projects/tap.procrastinate_tilde")
subdirs("source/projects/tap.pulsesub_tilde")
subdirs("source/projects/tap.radians_tilde")
subdirs("source/projects/tap.random")
subdirs("source/projects/tap.random_tilde")
subdirs("source/projects/tap.rotate")
subdirs("source/projects/tap.route")
subdirs("source/projects/tap.shift_tilde")
subdirs("source/projects/tap.sieve")
subdirs("source/projects/tap.sift_tilde")
subdirs("source/projects/tap.split_tilde")
subdirs("source/projects/tap.svf_tilde")
subdirs("source/projects/tap.verb_tilde")
subdirs("source/projects/tap.width_tilde")
subdirs("source/projects/tap.zerox_tilde")
